### ISSUE TITLE
Regarding PreCo dataset

### ISSUE THREAD

**Issue by KawshikManikantan** [gorka96/Coreference-Corpora-List#3]
The PreCo dataset (https://preschool-lab.github.io/PreCo/) seems to be unavailable as no email was received for many days after filling in the details on the page. Though I know this is not an issue of this repository, I could not place my hands on it anywhere and thought maybe the community can help me here. Can someone point me to any version of the dataset available elsewhere?
Thank you

**Comment by GorkaUrbizu** [comment]
I believe that I got the replay almost instantly after filling in the info.
So I would suggest contacting them directly (there is a contact email on their page).
Anyway, I'll keep the issue open, hoping someone can help. Good luck!

**Comment by KawshikManikantan** [comment]
@GorkaUrbizu thanks for the immediate reply. I tried multiple email ids and also mailed them a while ago and haven't gotten a reply. I am afraid that it has been down recently. If anyone could create a link for the downloadable link with the files I would be heavily grateful as it would help my academic research move forward.
