### ISSUE TITLE
CorefUD

### ISSUE THREAD

**Issue by AngledLuffa** [gorka96/Coreference-Corpora-List#5]
Can I point you in the direction of this project:

https://ufal.mff.cuni.cz/corefud

**Comment by GorkaUrbizu** [comment]
I already know the project (it was already listed on my list, under multilingual datasets) and I had the chance to meet people working on it during LREC 2022 and LREC-COLING 2024. Such an interested and needed project!
I was thinking on adding the Basque coref dataset in it, but unfortunately I changed on research topics for my PhD and I don't work on coreference anymore.

**Comment by AngledLuffa** [comment]
Good point, I'd missed the multilingual section
